@echo off
echo Đang build lại repository...
python create_repository.py --datadir="./" "./addons/a4kSubtitles-repository" "./addons/plugin.program.openwizard" "./addons/repository.jellyfin.kodi" "./addons/skin.arctic.zephyr.mod-master"
echo Build xong! Đang chờ sếp Push lên GitHub...
pause